name: Docker Image CI

on:
  pull_request:
    branches: 
      - master
      - staging
      - development
  push:
    branches: 
      - master
      - staging
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Pulling old images, if any
        run: docker-compose pull --ignore-pull-failures
      - name: Setting APP_ENV
        env:
         APP_ENV: dev
        run: echo "set APP_ENV to $APP_ENV"
      - if: contains( github.ref, 'master' ) || contains( github.base_ref, 'master' )
        env:
         APP_ENV: prod
        run: echo "set APP_ENV to $APP_ENV" 
      - if: contains( github.ref, 'staging' ) || contains( github.base_ref, 'staging' )
        env:
          APP_ENV: stag
        run: echo "set APP_ENV to $APP_ENV"  
      - name: Build the Docker image
        run: docker-compose build --pull --build-arg APP_ENV=$APP_ENV
      - name: Run the docker image
        run: docker-compose up -d
      - name: Taking some sleep
        run: sleep 100
      - name: Check if all containers are running
        run: docker ps
      - name: Dumping the logs
        run: docker-compose logs
      - name: Security Checks
        run: docker-compose exec -T php composer req sensiolabs/security-checker
      - name: Chores
        run: docker-compose down
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push to docker hub
        run: docker-compose push
      - name: Deploy through helm
        if: contains( github.ref, 'master' ) || contains( github.ref, 'staging' ) || contains( github.ref, 'development' )
        env:
            KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: helm install --name pc-$APP_ENV ./api/helm  --kubeconfig="$KUBECONFIG" --namespace=$APP_ENV  --set settings.env=$APP_ENV,settings.debug=1
